/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockIndexRouteImport } from './routes/stock/index'
import { Route as StockAddRouteImport } from './routes/stock/add'

const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockIndexRoute = StockIndexRouteImport.update({
  id: '/stock/',
  path: '/stock/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockAddRoute = StockAddRouteImport.update({
  id: '/stock/add',
  path: '/stock/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/stock/add': typeof StockAddRoute
  '/stock/': typeof StockIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/stock/add': typeof StockAddRoute
  '/stock': typeof StockIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal': typeof LegalRoute
  '/stock/add': typeof StockAddRoute
  '/stock/': typeof StockIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/legal' | '/stock/add' | '/stock/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/legal' | '/stock/add' | '/stock'
  id: '__root__' | '/' | '/legal' | '/stock/add' | '/stock/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalRoute: typeof LegalRoute
  StockAddRoute: typeof StockAddRoute
  StockIndexRoute: typeof StockIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/': {
      id: '/stock/'
      path: '/stock'
      fullPath: '/stock/'
      preLoaderRoute: typeof StockIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock/add': {
      id: '/stock/add'
      path: '/stock/add'
      fullPath: '/stock/add'
      preLoaderRoute: typeof StockAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalRoute: LegalRoute,
  StockAddRoute: StockAddRoute,
  StockIndexRoute: StockIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
